---
- name: clone/update repository
  git:
    accept_hostkey: true
    dest: ~/deploy/{{ product }}
    key_file: ~/.ssh/id_rsa
    repo: ssh://git@github.com/cavagrill/{{ product }}.git
    update: true
    force: true
    version: '{{ branch }}'
  register: git
- name: create virtualenv with up-to-date pip
  pip:
    extra_args: '--upgrade'
    name: pip,wheel,setuptools
    virtualenv: "{{ virtualenv[python_version]['directory'] }}"
    virtualenv_command: "{{ virtualenv[python_version]['command'] }}"
- name: install packages into virtualenv
  pip:
    extra_args: '--upgrade'
    requirements: ~/deploy/{{ product }}/requirements.txt
    virtualenv: "{{ virtualenv[python_version]['directory'] }}"
    virtualenv_command: "{{ virtualenv[python_version]['command'] }}"
- name: create cron jobs
  cron:
    day: '{{ item.day }}'
    disabled: false
    hour: '{{ item.hour }}'
    job: '{{ item.job }} >/var/log/cron/{{ item.name }}.log'
    minute: '{{ item.minute }}'
    month: '{{ item.month }}'
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    user: '{{ user }}'
    weekday: '{{ item.weekday }}'
  with_items: '{{ cron_jobs }}'
  when: do_cron is defined and do_cron
- name: configure cron shell
  cron:
    name: SHELL
    value: "/bin/bash"
    env: yes
  when: do_cron is defined and do_cron
- name: configure cron mail
  cron:
    name: MAILTO
    value: "{{ slack_email }}"
    env: yes
  when: do_cron is defined and do_cron
- name: configure cron path
  cron:
    name: PATH
    value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    env: yes
  when: do_cron is defined and do_cron
- name: create .pip directory
  become_user: root
  file:
    path: /home/{{ user }}/.pip
    owner: '{{ user }}'
    group: '{{ user }}'
    state: directory
- name: install pip.conf
  become_user: root
  copy:
    src: pip.conf
    dest: /home/{{ user }}/.pip/pip.conf
    owner: '{{ user }}'
    group: '{{ user }}'
- name: tell slack what happened
  slack:
    color: good
    msg: '{{ branch }} branch of {{ product }} has been deployed to {{ inventory_hostname}}.'
    token: '{{ slack_token }}'
  become: false
  delegate_to: localhost
  when: notify_slack is defined and notify_slack
